name: Deploy to GitHub Packages

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.4"

      - name: Install Kamal
        run: gem install kamal

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker registry
        env:
          KAMAL_REGISTRY_USERNAME: ${{github.actor}}
          KAMAL_REGISTRY_PASSWORD: ${{secrets.GITHUB_TOKEN}}

        run: |
          echo "${KAMAL_REGISTRY_PASSWORD}" | docker login ghcr.io -u "${KAMAL_REGISTRY_USERNAME}" --password-stdin

      - name: Build and Push with Kamal
        env:
          KAMAL_REGISTRY_PASSWORD: ${{secrets.GITHUB_TOKEN}}
          KAMAL_SSH_KEY: ${{ secrets.KAMAL_SSH_KEY }}

        run: |
          kamal build
          kamal deploy
